backgrounds:
  - https://i.loli.net/2018/08/07/5b691474e1e2c.jpg
  - https://i.loli.net/2018/08/07/5b69147dbeb36.jpg
  - https://i.loli.net/2018/08/07/5b69147ee7d1f.jpg
  - https://i.loli.net/2018/08/07/5b691486d368d.jpg
  - https://i.loli.net/2018/08/07/5b691488c26a5.jpg


navbar:
  - name: 首页
    icon: fa fa-home
    url: /
  - name: 归档
    icon: fa fa-archive
    url: /archives
  - name: 标签
    icon: fa fa-tags
    url: /tags
  - name: 分类
    icon: fa fa-folder
    url: /categories
#  - name: 友人帐
#    icon: fa fa-address-book
#    url: /friends
  - name: 关于我
    icon: fa fa-user-secret
    url: /about
